services:
  spark-master:
    image: spark:3.5.2
      #    build: dockerfiles/spark
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    environment:
      SPARK_PUBLIC_DNS: localhost
    ports:
      - 4040:4040
      - 8080:8080
    volumes:
      - ./data/spark-master:/tmp/data
      - ./migrator/target/scala-2.13:/jars
      - ./parquet-data:/parquet-data
      - ./:/app

  spark-worker:
    image: spark:3.5.2
    #    build: dockerfiles/spark
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    environment:
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 4G
      SPARK_WORKER_WEBUI_PORT: 8081
      SPARK_PUBLIC_DNS: localhost
    ports:
      - 8081:8081
    volumes:
      - ./data/spark-worker:/tmp/data
      - ./parquet-data:/parquet-data
    depends_on:
      - spark-master
